name: Sync to Hugging Face hub
on:
  push:
    branches: [main]


  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://mahedi420:$HF@huggingface.co/spaces/mahedi420/mle2e
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://mahedi420:$HF@huggingface.co/spaces/mahedi420/mle2e main